apiVersion: v1
kind: Service
metadata:
  name: paymentdeliveryhost
  annotations:
    cloud.google.com/neg: '{"exposed_ports":{"80":{}}}'
  labels:
    app: paymentdelivery
spec:
  ports:
  - port: 80
    targetPort: 5001
    protocol: TCP
    name: http
  selector:
    app: paymentdelivery
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-payment-next19-delivery-asia-southeast1-b
  annotations:
    traffic.sidecar.istio.io/includeOutboundIPRanges: "10.128.0.4,10.128.0.6"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: paymentdelivery
        version: v1
    spec:
      containers:
      - name: paymentdelivery
        env:
        - name: DATACENTER
          value: asia-southeast1-b
        - name: CART_HOST
          value: http://10.128.0.4
        - name: PAYMENT_HOST
          value: http://10.128.0.6
        - name: PORT
          value: "5001"
        - name: CONTROL_PLANE
          value: control-plane-next19
        image: us.gcr.io/traffic-director-demo/payment-service-next19-delivery:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
      - image: docker.io/istio/proxyv2:1.1.0-rc.3
        imagePullPolicy: IfNotPresent
        name: istio-proxy
        ports:
        - containerPort: 15090
          name: http-envoy-prom
          protocol: TCP
        args:
        - proxy
        - sidecar
        - --domain
        - $(POD_NAMESPACE).svc.cluster.local
        - --configPath
        - /etc/istio/proxy
        - --binaryPath
        - /usr/local/bin/envoy
        - --serviceCluster
        - $(POD_NAMESPACE)
        - --drainDuration
        - 45s
        - --parentShutdownDuration
        - 1m0s
        - --discoveryAddress
        - trafficdirector.googleapis.com:443
        - --connectTimeout
        - 10s
        - --proxyAdminPort
        - "15000"
        - --concurrency
        - "2"
        - --statusPort
        - "15020"
        env:
        - name: ISTIO_BOOTSTRAP
          value: "/var/lib/istio/envoy/gcp_envoy_bootstrap_tmpl.json"
        - name: ISTIO_META_TRAFFICDIRECTOR_INTERCEPTION_PORT
          value: "15001"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ISTIO_META_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /healthz/ready
            port: 15020
          initialDelaySeconds: 1
          periodSeconds: 2
        resources:
          limits:
            cpu: "2"
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 1337
        volumeMounts:
        - mountPath: /etc/istio/proxy
          name: istio-envoy
      initContainers:
      - args:
        - -p
        - "15001"
        - -u
        - "1337"
        - -m
        - REDIRECT
        - -i
        - "10.128.0.4,10.128.0.6"
        - -x
        - ""
        - -d
        - "15020"
        env:
        - name: DISABLE_REDIRECTION_ON_LOCAL_LOOPBACK
          value: "true"
        image: docker.io/istio/proxy_init:1.1.0-rc.3
        imagePullPolicy: IfNotPresent
        name: istio-init
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 10Mi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
      volumes:
      - emptyDir:
          medium: Memory
        name: istio-envoy
      hostAliases:
      - ip: 10.128.0.6
        hostnames:
          - paymentdeliveryhost